language: java
jdk:
- oraclejdk7
before_deploy:
  - ./gradlew build
  - export THE_JAR=$(ls build/libs/JAPTA*.jar | head -n 1)
  - echo "found $THE_JAR for deploying"
deploy:
  - provider: releases
    api_key:
      secure: Gv2Ng3JWeJyzlBGpdndfMmebvDVEOAK0ZxzW42kBzKpaqs6inYZuYf7BVkto5A8/wuz7HmStAATqPpTXRJElPH8qEc6l3Wg8UflG9cshLxwqtNIgHKl0qOrlktasR1tslGetFvfRS3oduuRHyIUR1fCJBb59G1II0nvuRrQMoOdUGZ3BAg2lMVp0PvCIKDIqokjeGpV4VXrRQdt62ozZLl6+dpqBUx8mILdEx7AWtFlXpyujOSLviGCB+XgdXVTsTWAJLN0GZvJ+jAnRIbVUl0+aNkqPD4qAE5g3raLXt7fuZC+wkmZ94OeaGq5AuXx5yZG2U6+fB9HMKsgUo/E7QEXcYrXWFkXVuRZv6tash38GWfG6aqBaQ4t+hAKSGAlpAB5IZVcDUWDHrAB91Mo4PW5OhzC+r/YO+TKQyoLAQeqtkrjVV7Ou4AQRpdd/uoyp6CGiyyokpL4tuZszlAiiAnmKDBOHuPUNePqpTpDeMozYhVTBe6aANy+yrt8FNQK2kZdOQof3u7X06xd3euoTVEP4uqP/WpMgiW3abwcXPwchDZw5mg5vCZuyzLUmePkdvDct46eA2DUcNN5CIVeBmPlrOTuQ+0Pq+iCZm/X/X0ojbXWRIatfD7O8/u06y/7IOql3/8/61xWliwxQqOo0cuQ+2Bmj9RXkjDcDLJbrIiA=
    file: "${THE_JAR}"
    on:
      repo: vpzomtrrfrt/JAPTA-1.9
      all_branches: true
      tags: true
    prerelease: true
  - provider: script
    script: ./gradlew curseforge
    on:
      repo: vpzomtrrfrt/JAPTA-1.9
      all_branches: true
      tags: true
